config/routes.rb
Rails.application.routes.draw do
  get '/nasad', to: redirect('/')

  get 'login' => 'sessions#new', as: 'login'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy', as: 'logout'
  resources :users

  get '/submit', to: 'submissions#new', as: 'new_submission'
  resources :submissions

  namespace :browse do
    resources :submissions, only: [:index, :show]
    resources :works, only: [:index, :show]
  end

  resources :syllabi
  resources :projects
  resources :courses
  resources :instructors
  resources :students
  resources :works
  resources :attachments, only: [:create, :destroy]

  get '/pdf', to: 'application#download_pdf', as: 'download_pdf'

  root 'application#index'

end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  has_many :works
  has_many :syllabi
  has_many :courses, through: :works#, uniq: true
  has_many :projects, through: :works#, uniq: true
  
  validates_presence_of :name

  def to_s
    self.name
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.all
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to @instructor, notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'Instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'Instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:name)
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<section class="row">
  <%= form_for(@instructor) do |f| %>
    <% if @instructor.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

        <ul>
        <% @instructor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="small-12 columns">
      <paper-material elevation="1" style="background: #fff; padding: 10px 20px;">
        <div class="field">
          <%= f.label :name, class: 'required' %>
          <%= f.text_field :name %>
        </div>
      </paper-material>

      <hr>
    </div>

    <div class="small-12 columns">
      <%= f.submit %>
      <%= link_to 'Cancel', instructors_path %>
    </div>
  <% end %>
</section>

app/views/instructors/edit.html.erb
<section class="row">
  <h1 class="small-12 columns">Edit Instructor</h1>
</section>

<%= render 'form' %>

app/views/instructors/index.html.erb
<section class="row">
  <div class="medium-8 columns">
    <h1>Instructors</h1>
  </div>
  <div class="medium-4 columns">
    <%= button_link_to 'New', new_instructor_path %>
  </div>

  <div class="small-12 columns">
    <table class="responsive">
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @instructors.each do |instructor| %>
          <tr>
            <td><%= instructor.name %></td>
            <td class="actions"><%= link_to 'View', instructor %></td>
            <td class="actions"><%= link_to 'Edit', edit_instructor_path(instructor) %></td>
            <td class="actions"><%#= link_to 'Destroy', instructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  
  <div class="small-6 columns end">
    <%= button_link_to 'New Instructor', new_instructor_path %>
  </div>
</section>

app/views/instructors/new.html.erb
<section class="row">
  <h1 class="small-12 columns">Add New Instructor</h1>
</section>

<%= render 'form' %>

app/views/instructors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @instructor.name %>
</p>

<%= link_to 'Edit', edit_instructor_path(@instructor) %> |
<%= link_to 'Back', instructors_path %>