config/routes.rb
Rails.application.routes.draw do
  get '/nasad', to: redirect('/')

  get 'login' => 'sessions#new', as: 'login'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy', as: 'logout'
  resources :users

  get '/submit', to: 'submissions#new', as: 'new_submission'
  resources :submissions

  namespace :browse do
    resources :submissions, only: [:index, :show]
    resources :works, only: [:index, :show]
  end

  resources :syllabi
  resources :projects
  resources :courses
  resources :instructors
  resources :students
  resources :works
  resources :attachments, only: [:create, :destroy]

  get '/pdf', to: 'application#download_pdf', as: 'download_pdf'

  root 'application#index'

end

app/models/submission.rb
class Submission < ActiveRecord::Base
  serialize :data, Hash

  attr_accessor :temp_image_token

  belongs_to :student
  has_many :attachments, as: :parent
  accepts_nested_attributes_for :student
  validates_presence_of :student

  # may want to add has_images boolean column like Work

end

app/controllers/browse/submissions_controller.rb
class Browse::SubmissionsController < ApplicationController
  before_action :login_required

  layout 'browse'
  before_filter :load_nav_objects
  before_filter :load_submissions
  before_filter :set_use_remote

  def index
  end

  def show
    # @work = Work.find(params[:id])
    @submission = Submission.find(params[:id])
  end

  private
    def set_use_remote
      @use_remote = false
    end

    def load_nav_objects
      @categories     = ['Painting', 'Sculpture', 'Computer Graphic', 'Drawing', 'Photograph', "Ceramic", 'Video/DVD Production', 'Printmaking', 'Mixed Media']
      @grades         = [6, 7, 8, 9, 10, 11, 12]
      # @areas        = Course.areas
      # @courses      = Course.where(has_works: true).order('number ASC')
      # @instructors  = Instructor.where(has_works: true).order('name ASC')
      # @levels       = ['Freshman', 'Sophomore', 'Junior', 'Senior']
    end

    def load_submissions
      @submissions = Submission.all

      if !params[:grade].blank?
        @submissions = @submissions.where("data like ?", "%Grade: '#{params[:grade].to_i}'%")
      end

      if !params[:category].blank?
        # To sanatize, make sure category param is in list of options
        category = (@categories & [params[:category]])[0]
        if category
          @submissions = @submissions.where("data like ?", "%Entry Category: #{category}%")
        end
      end


    end

    def load_works
      # if !params[:project].nil?
      #   @project        = Project.find_by_id(params[:project])
      #   params[:course] = @project.try(:course).try(:id)
      # end
      #
      # if !params[:instructor].nil?
      #   @instructor     = Instructor.find_by_id(params[:instructor])
      # end
      #
      # if !params[:course].nil?
      #   @course         = Course.find_by_id(params[:course])
      #   # params[:level] = Course.find_by_id(params[:course]).try(:level)
      # end
      #
      # if !params[:course].blank?
      #   # just select course
      #   course_ids = params[:course]
      #
      # elsif !params[:level].blank? && !params[:area].blank?
      #   # combine course ids
      #   course_ids = Course.where(level: params[:level]).ids & Course.where(area: params[:area]).ids
      #
      # elsif !params[:level].blank?
      #   # select just level courses
      #   course_ids = Course.where(level: params[:level]).ids
      #
      # elsif !params[:area].blank?
      #   # select just area courses
      #   course_ids = Course.where(area: params[:area]).ids
      #
      # else
      #   # ignore course ids
      #   course_ids = nil
      # end
      #
      # conditions = {}
      # conditions.merge!({instructor_id: params[:instructor]})                  unless params[:instructor].blank?
      # conditions.merge!({project_id: params[:project]})                        unless params[:project].blank?
      # conditions.merge!({course_id: course_ids})                               unless course_ids.blank?
      #
      # conditions.merge!({has_images: true})                                    if params[:only_images] == 't'
      #
      # unless conditions.blank?
      #   @works = Work.where({has_attachments: true}.merge(conditions)).order('created_at DESC').includes(:instructor, :course, :project)
      # end
    end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  skip_before_action :login_required
  before_action :set_submission, only: [:show, :edit, :update, :destroy]
  before_action :login_required, except: [:new, :create] # SubmissionsController overrides the normal method, but must come after `set_submission`
  before_action :prevent_reviewer_access


  layout 'submit'

  # GET /submissions
  # GET /submissions.json
  def index
    @submissions = Submission.all
    @custom_fields = CustomField.all.map(&:name)

    respond_to do |format|
      format.html
      format.csv { send_data render_to_string('index.csv', layout: false), type: 'text/csv; charset=utf-8' }
    end
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
  end

  # GET /submissions/new
  def new
    @previous_submission = Submission.find_by_id(session[:previous_submission_id])
    @submission = Submission.new(temp_image_token: Random.rand(10000000..999999999))
    @submission.build_student()

    if @previous_submission
      CustomField.where(persistent: true).each do |custom_field|
        @submission.data[custom_field.name] = @previous_submission.data[custom_field.name]
      end
    end
  end

  # GET /submissions/1/edit
  def edit
    @submission.temp_image_token = Random.rand(10000000..999999999)
  end

  # POST /submissions
  # POST /submissions.json
  def create
    @submission = Submission.new(submission_params)

    respond_to do |format|
      if @submission.save
        move_temp_ajax_images(@submission)
        session[:previous_submission_id] = @submission.id

        # Store uploaded submissions from this session
        # This allows these submissions to be viewed or edited without logging
        session[:uploaded_submission_ids] ||= []
        session[:uploaded_submission_ids] << @submission.id

        format.html { redirect_to @submission, notice: 'Submission was successfully uploaded.' }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submissions/1
  # PATCH/PUT /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        move_temp_ajax_images(@submission)

        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_params
      params.require(:submission).permit(:temp_image_token, data: CustomField.fields, student_attributes: [:id, :name])
    end

    def move_temp_ajax_images(submission=@submission)
      Attachment.where(parent_id: submission.temp_image_token, parent_type: 'temp').each do |attachment|
        attachment.parent = submission
        attachment.save
      end
    end

    # This overrides the normal login behavior to allow viewing and editing of submissions uploaded during this session
    def login_required
      session[:uploaded_submission_ids] ||= [] # in case it hasn't yet been set

      if @submission && session[:uploaded_submission_ids].include?(@submission.id)
        # return true will simply allow the application to continue, ignoring the normal login method (return true does not mean that login is required)
        return true
      else
        super
      end
    end
end

app/helpers/browse/submissions_helper.rb
module Browse::SubmissionsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
  def categories_array(submission)
    # this is specific to mtrsae
    #
    categories = []
    categories << submission.data['Entry 1 Category'] unless submission.data['Entry 1 Category'].blank?
    categories << submission.data['Entry 2 Category'] unless submission.data['Entry 2 Category'].blank?
    return categories
  end
  def categories(submission)
    # this is specific to mtrsae
    #
    return categories_array(submission).uniq.compact.join(' & ')
  end
end

app/views/submissions/_form.html.erb
<style media="screen">
  body {
    background-color: #efefef;
  }
</style>

<section class="row">
  <div class="large-8 medium-10 large-offset-2 medium-offset-1 columns">
    <p>
      <b>By submitting this form, students and teachers agree to the below statement:</b><br>
      I give permission for the Leu Center for the Visual Arts to display my art and to use it in any promotional materials created for the Middle Tennessee Regional Student Art Exhibition. I fully understand that the Leu Center for the Visual Arts and the MTRSAE Committee will take reasonable care of entries and that I must reclaim my work by the date requested. I understand that Belmont University will assume no liability for lost or damaged work. I also understand that if selected for the Best of the Best exhibition my work cannot be picked up until the conclusion of that exhibition. Also, if selected as Best of Show my artwork will be purchased for a permanent collection.
    </p>

    <p><b>Please submit one entry per student at a time.</b> There is a maximum of two entries per student.</p>
  </div>
</section>

<%= form_for(@submission, html: {id: 'submission_form'}) do |f| %>
  <% if @submission.errors.any? %>
    <section class="row">
      <div class="large-8 medium-10 large-offset-2 medium-offset-1 columns" id="error_explanation">
        <h2><%= pluralize(@submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

        <ul>
        <% @submission.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </section>
  <% end %>



<section class="row">
  <div class="large-8 medium-10 large-offset-2 medium-offset-1 columns">
    <%= box do %>
      <%= box_body do %>

        <%= label_tag nil, 'Images and Files', class: 'required' %>
        <div id="upload-works" style="border: 1px dashed #ccc;" class="dropzone"></div>

        <%
          if @submission.new_record? && @submission.errors.any?
            previously_uploaded = Attachment.where(parent_type: 'temp', parent_id: @submission.temp_image_token)
          elsif !@submission.new_record?
            previously_uploaded = @submission.attachments
          else
            previously_uploaded = nil
          end
        %>
        <% if previously_uploaded && previously_uploaded.count > 0 %>
          <div class="notice success">
            <%= pluralize(previously_uploaded.count, 'file') %> <%= previously_uploaded.count == 1 ? 'has' : 'have' %> already been uploaded. You do not need to re-upload <%= previously_uploaded.count == 1 ? 'this file' : 'these files' %>:
          </div>
          <div>
            <% previously_uploaded.each do |attachment| %>
              <% if attachment.file_content_type.include?('image') %>
                <%= image_tag attachment.file.url(:small) %>
              <% else %>
                <%= link_to attachment.file.url(), class: 'file-attachment medium' do %>
                  <%= file_icon(attachment.file_content_type) %><br>
                  <%= attachment.file_file_name %>
                <% end %>
              <% end %>
            <% end %>
          </div>
        <% end %>

      <% end #box_body %>
    <% end #box %>
  </div>
</section>


<section class="row">
  <div class="large-8 medium-10 large-offset-2 medium-offset-1 columns">
    <%= box do %>
      <%= box_body do %>

        <%# --- Student ---- %>
        <%= f.fields_for :student do |f_student| %>
          <%= f_student.hidden_field :id %>
          <%= text_field_with_bar f_student, :name, label: 'Student Name', required: true %>
        <% end %>

        <%# --- Custom Fields ---- %>
        <%= f.fields_for :data, OpenStruct.new(f.object.data || {}) do |f_data| %>
          <% CustomField.all.each do |custom_field| %>
            <div class="field">
              <% if custom_field.options.any? %>
                <%= chosen_select f_data, custom_field.name, options_for_select(custom_field.options.map(&:name), f.object[custom_field.name]), include_blank: (custom_field.options.count > 1), label: true, required: custom_field.required %>
              <% else %>
                <% if custom_field.input_type == 'textarea' %>
                  <%= text_area_with_bar f_data, custom_field.name, label: true, required: custom_field.required %>
                <% else %>
                  <%= text_field_with_bar f_data, custom_field.name, label: true, required: custom_field.required %>
                <% end %>
              <% end %>
            </div>
          <% end %>
        <% end %>


      <% end #box_body %>
    <% end #box %>
  </div>
</section>


<section class="row">
  <div class="large-8 medium-10 large-offset-2 medium-offset-1 columns actions text-right" style="margin-bottom: 5em;">
    <%= f.hidden_field :temp_image_token %>
    <%= f.submit "#{@submission.new_record? ? 'Submit' : 'Update'} Entry" %>
    <%= link_to 'Cancel Changes', @submission, class: 'cancel' unless @submission.new_record? %>
  </div>
</section>

<% end %>


<script type="text/javascript">
var dropzoneFileCount = 0;
var dropzoneFileCompleted = 0;
var dropzoneFileSuccessCount = 0;

var submit_button = $('#submission_form input[type="submit"]');
submit_button.data('defaultVal', submit_button.val());

var myDropzone = new Dropzone("div#upload-works", {
  url: "<%= attachments_path(temp_image_token: @submission.temp_image_token) %>",
  paramName: "attachment[file]",
  dictDefaultMessage: 'Drop <%= "additional" if !@submission.new_record? %> files here or click to upload',
  init: function() {
    this.on("addedfile", function(file) {
      dropzoneFileCount += 1;

      submit_button.val('Uploading file, please wait...')
      submit_button.attr('disabled', 'disabled');

      $('#notice-container .notice.uploading').removeClass('hide');

      if (dropzoneFileCount > 1) {
        $('#notice-container .plural').removeClass('hide');
        $('#notice-container .total-file-count').html(dropzoneFileCount);
      }
    });
    this.on('error', function(file) {
      $('#notice-container').append('<div class="notice error">There was an error while uploading <span class="filename">' + file.name + '</span></div>');
    });
    this.on('success', function(file) {
      dropzoneFileSuccessCount += 1;

      $('#notice-container .success').removeClass('hide');
      $('#notice-container .file-count').html(dropzoneFileSuccessCount);
    });
    this.on('complete', function(file) {
      dropzoneFileCompleted += 1;

      if (dropzoneFileCompleted == dropzoneFileCount) {
        $('#notice-container .notice.uploading').addClass('hide');
        submit_button.val(submit_button.data('defaultVal'));
        submit_button.removeAttr('disabled');
      }
    });
  }
});
</script>

app/views/submissions/edit.html.erb
<section class="row">
  <div class="large-8 medium-10 large-offset-2 medium-offset-1 columns">
    <h1>Edit Student Submission</h1>
  </div>
</section>

<%= render 'form' %>

app/views/submissions/index.csv.erb
id,Name,<%= @custom_fields.join(',').html_safe %>,Submission Date
<% @submissions.each do |submission| %>
<%= submission.id %>,"<%= submission.student.to_s %>",<%= @custom_fields.map{|field| "\"#{submission.data[field].gsub('"', "'")}\""}.join(',').html_safe %>,<%= submission.created_at.to_s(:date_slashed_full) %>
<% end %>

app/views/submissions/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="medium-8 columns">
    <h1>Listing Submissions</h1>
  </div>
  <div class="medium-4 columns medium-text-right">
    <%= link_to 'Download CSV', submissions_path(format: [:csv]), class: 'button ' %>
  </div>
</div>


<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @submissions.each do |submission| %>
      <tr>
        <td><%= submission.student %></td>
        <td><%= submission.data %></td>
        <td><%= link_to 'Show', submission %></td>
        <td><%= link_to 'Edit', edit_submission_path(submission) %></td>
        <td><%= link_to 'Destroy', submission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Submission', new_submission_path %>

app/views/submissions/new.html.erb
<section class="row">
  <div class="large-8 medium-10 large-offset-2 medium-offset-1 columns">
    <h1>New Student Submission</h1>
  </div>
</section>

<%= render 'form' %>

app/views/submissions/show.html.erb
<style media="screen">
  th {
    width: 275px;
  }
</style>

<section class="row">
  <div class="columns">
    <%= box do %>
      <%= box_heading title: 'Submission Info' %>
      <%= box_body do %>
        <table style="width: 100%;">
          <tbody>
            <tr>
              <th>Student Name</th>
              <td><%= @submission.student %></td>
            </tr>

            <% @submission.data.each do |key, value| %>
              <% unless value.blank? %>
                <tr>
                  <th><%= key %></th>
                  <td><%= value %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      <% end #box_body %>
    <% end #box %>

    <%= box do %>
      <%= box_heading title:'File Preview' %>
      <%= box_body do %>

        <% if @submission.attachments.empty? %>
          <p class="notice error">No files were uploaded</p>
        <% end %>

        <% @submission.attachments.each do |attachment| %>
          <% if attachment.file_content_type.include?('image') %>
            <%= image_tag attachment.file.url(:small) %>
          <% else %>
            <%= link_to attachment.file.url(), class: 'file-attachment medium' do %>
              <%= file_icon(attachment.file_content_type) %><br>
              <%= attachment.file_file_name %>
            <% end %>
          <% end %>
        <% end %>

      <% end %>
    <% end %>
  </div>
</section>



<%= link_to 'Edit', edit_submission_path(@submission) %> |
<%= link_to 'Submit More', new_submission_path %>