config/routes.rb
Rails.application.routes.draw do
  get '/nasad', to: redirect('/')

  get 'login' => 'sessions#new', as: 'login'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy', as: 'logout'
  resources :users

  get '/submit', to: 'submissions#new', as: 'new_submission'
  resources :submissions

  namespace :browse do
    resources :submissions, only: [:index, :show]
    resources :works, only: [:index, :show]
  end

  resources :syllabi
  resources :projects
  resources :courses
  resources :instructors
  resources :students
  resources :works
  resources :attachments, only: [:create, :destroy]

  get '/pdf', to: 'application#download_pdf', as: 'download_pdf'

  root 'application#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :course
  has_many :works
  has_many :instructors, through: :works #, uniq: true

  def to_s
    self.name
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    if params[:course_id]
      @course = Course.find(params[:course_id])
      @projects = @course.projects
    else
      @projects = Project.all
    end

    respond_to do |format|
      format.html {}
      format.json {render :json => @projects.as_json}
      format.js {}
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :course_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.text_field :course_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_select_field.html.erb
<%
  f         ||= ActionView::Helpers::FormBuilder.new(:work, Work.new, self, {})
  projects  ||= @projects
  projects  ||= @work.course.projects rescue nil
  projects  ||= @course.projects rescue nil
  projects  ||= Project.all
%>
<%= 
  chosen_select(f, :project_id, options_from_collection_for_select(projects, 'id', 'name', @work.try(:project_id)), {include_blank: true}, 
    'data-no_results_text' => 'No projects found. Press enter/return to create new project named',
    'data-max_selected_options' => '1',
    multiple: true,
    data: {
      placeholder: 'Select or create a project',
      allow_new: true
    }
  ) 
%>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<section class="row">
  <div class="small-12 columns">
    <h1>Projects</h1>
  </div>

  <div class="small-12 columns">
    <table class="responsive">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Course</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @projects.each do |project| %>
          <tr>
            <td><%= project.name %></td>
            <td><%= project.description %></td>
            <td><%= project.course %></td>
            <td class="actions"><%= link_to 'Show', project %></td>
            <td class="actions"><%= link_to 'Edit', edit_project_path(project) %></td>
            <td class="actions"><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
 </div>

  <div class="small-6 columns end">
    <%#= button_link_to 'New Project', new_project_path %>
  </div>
</section>

app/views/projects/index.js.erb
// alert("Number of projects: <%= @projects.count %>");

$('#projects-container').html("<%= escape_javascript render(partial: 'projects/select_field') %>");


// dynamically load project description
$('#work_project_id').change(function() {
  project_id = $('#work_project_id').val();
  if (project_id != null) {
    url = '<%= project_path("--placeholder--", format: :json) %>'.replace('--placeholder--', project_id[0]);
    $.ajax({
      url: url,
      beforeSend: function() {
        // $().html('<div class="ajax-loading-spinner"></div>');
      },
      success: function(data) {
        // do other things
        $('#project_description').removeAttr('disabled').removeAttr('placeholder');
        $('#project_description').val(data.description);
      }
    })
  } else {
    $('#project_description').attr('disabled', 'disabled').attr('placeholder', 'Select or create a project first');
    $('#project_description').val('');
  }
  
})

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Course:</strong>
  <%= @project.course %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>